export const Candidates = [
  {
    id: 1,
    name: "Mohammed Mohammed",
    email: "mohammed@gmail.com",
    applyedDate: "January 7, 2020",
    isPhoneScreeningCompleted: true,
  },
  {
    id: 2,
    name: "Yassine Yassine",
    email: "yassine@gmail.com",
    applyedDate: "January 7, 2020",
    isPhoneScreeningCompleted: true,
  },
  {
    id: 3,
    name: "Youness Youness",
    email: "youness@gmail.com",
    applyedDate: "January 7, 2020",
    isPhoneScreeningCompleted: true,
  },
  {
    id: 4,
    name: "Karim Karim",
    email: "karim@gmail.com",
    applyedDate: "January 7, 2020",
    isPhoneScreeningCompleted: true,
  },
  {
    id: 5,
    name: "Lamia Lamia",
    email: "Lamia@gmail.com",
    applyedDate: "January 7, 2020",
    isPhoneScreeningCompleted: true,
  },
  {
    id: 6,
    name: "Sana Sana",
    email: "sana@gmail.com",
    applyedDate: "January 5, 2020",
    isPhoneScreeningCompleted: true,
  },
  {
    id: 7,
    name: "Khalid Khalid",
    email: "khalid@gmail.com",
    applyedDate: "January 7, 2020",
    isPhoneScreeningCompleted: true,
  },
  {
    id: 8,
    name: "Hassan Hassan",
    email: "hasan@gmail.com",
    applyedDate: "January 7, 2020",
    isPhoneScreeningCompleted: true,
  },
  {
    id: 9,
    name: "Mohammed Mohammed",
    email: "mohammed@gmail.com",
    applyedDate: "January 7, 2020",
    isPhoneScreeningCompleted: true,
  },
  {
    id: 10,
    name: "Mohammed Mohammed",
    email: "mohammed@gmail.com",
    applyedDate: "January 7, 2020",
    isPhoneScreeningCompleted: false,
  },
  {
    id: 11,
    name: "Mohammed Mohammed",
    email: "mohammed@gmail.com",
    applyedDate: "January 7, 2020",
    isPhoneScreeningCompleted: true,
  },
  {
    id: 12,
    name: "Mohammed Mohammed",
    email: "mohammed@gmail.com",
    applyedDate: "January 7, 2020",
    isPhoneScreeningCompleted: true,
  },
  {
    id: 13,
    name: "Mohammed Mohammed",
    email: "mohammed@gmail.com",
    applyedDate: "January 7, 2020",
    isPhoneScreeningCompleted: true,
  },
  {
    id: 14,
    name: "Mohammed Mohammed",
    email: "mohammed@gmail.com",
    applyedDate: "January 7, 2020",
    isPhoneScreeningCompleted: true,
  },
  {
    id: 15,
    name: "Mohammed Mohammed",
    email: "mohammed@gmail.com",
    applyedDate: "January 7, 2020",
    isPhoneScreeningCompleted: true,
  },
  {
    id: 16,
    name: "Mohammed Mohammed",
    email: "mohammed@gmail.com",
    applyedDate: "January 7, 2020",
    isPhoneScreeningCompleted: false,
  },
  {
    id: 17,
    name: "Mohammed Mohammed",
    email: "mohammed@gmail.com",
    applyedDate: "January 7, 2020",
    isPhoneScreeningCompleted: true,
  },
  {
    id: 18,
    name: "Mohammed Mohammed",
    email: "mohammed@gmail.com",
    applyedDate: "January 7, 2020",
    isPhoneScreeningCompleted: true,
  },
  {
    id: 19,
    name: "Mohammed Mohammed",
    email: "mohammed@gmail.com",
    applyedDate: "January 7, 2020",
    isPhoneScreeningCompleted: true,
  },
  {
    id: 20,
    name: "Mohammed Mohammed",
    email: "mohammed@gmail.com",
    applyedDate: "January 7, 2020",
    isPhoneScreeningCompleted: true,
  },
  {
    id: 21,
    name: "Mohammed Mohammed",
    email: "mohammed@gmail.com",
    applyedDate: "January 7, 2020",
    isPhoneScreeningCompleted: true,
  },
];
